package jdbcdemo.dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import jdbcdemo.domain.Person;

public class PersonRepository extends RepositoryBase<Person>{



	@Override
	protected String selectAllSql() {
		return "SELECT * FROM person";
	}

	@Override
	protected String deleteSql() {
		return "DELETE FROM person WHERE id=?";
	}

	@Override
	protected String updateSql() {
		return "UPDATE person SET (name, surname, age) = (?,?,?) WHERE id=?";

	}

	@Override
	protected String insertSql() {
		return "INSERT INTO person(name,surname,age) VALUES (?,?,?)";
	}

	@Override
	protected String tableName() {
		return "person";
	}

	@Override
	protected String createTableSql() {
		return "CREATE TABLE person("
				+ "id INT GENERATED BY DEFAULT AS IDENTITY,"
				+ "name VARCHAR(20),"
				+ "surname VARCHAR(50),"
				+ "age INT"
				+ ")";
	}


	Connection connection;

	private String createTableSql = "CREATE TABLE person("
			+ "id INT GENERATED BY DEFAULT AS IDENTITY,"
			+ "name VARCHAR(20),"
			+ "surname VARCHAR(50),"
			+ "age INT"
			+ ")";

	private String insertSql = "INSERT INTO person(name,surname,age) VALUES (?,?,?)";
	private String updateSql = "UPDATE person SET (name, surname, age) = (?,?,?) WHERE id=?";
	private String deleteSql = "DELETE FROM person WHERE id=?";
	private String selectAllSql = "SELECT * FROM person";

	private Statement createTable;
	private PreparedStatement insert;
	private PreparedStatement selectAll;
	private PreparedStatement update;
	private PreparedStatement delete;

	public PersonRepository(){
		super();
	}

	public List<Person> getAll(){
		List<Person> result = new ArrayList<Person>();
		try {
			ResultSet rs = selectAll.executeQuery();
			while(rs.next()){
				Person p = new Person();
				p.setId(rs.getInt("id"));
				p.setName(rs.getString("name"));
				p.setSurname(rs.getString("surname"));
				p.setAge(rs.getInt("age"));
				result.add(p);
			}


		} catch (SQLException e) {
			e.printStackTrace();
		}
		return result;
	}




}
